name: Deploy Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy-main:
    env:
      APP_DEPLOY_HOOK: ${{secrets.APP_DEPLOY_HOOK}}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create Release
        run: curl "$APP_DEPLOY_HOOK"
