name: Deploy Main

on:
  push:
    branches:
      - 'main'
jobs:
  deploy-main:
    env:
      APP_DEPLOY_HOOK: ${{secrets.APP_DEPLOY_HOOK}}
    runs-on: ubuntu-latest
    needs: [test, deploy-staging]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create Release
        run: curl "$APP_DEPLOY_HOOK"
