# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs



name: "Github Actions Test"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PORT: 3000
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      CONNECTION_STRING: ${{secrets.CONNECTION_STRING}}
      NODE_ENV: test
      DB: ${{secrets.DB}}
      SERVER_URL: "http://localhost:3000"
      ROOT_API_VERSION_PATH: "api/v1"
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      JWT_EXPIRES_IN: "90d"

    steps:
      - uses: actions/checkout@v1
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: "Install deps"
        run: npm install
      - name: "start"
        run: yarn test:start
      - name: "Start backend and frontend concurrently on background and run tests"
        run: |
          yarn test

